export interface Product {
  id: string;
  name: string;
  slug: string;
  description: string;
  image: string;
  categories: string[];
  specifications?: string[];
  features?: string[];
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Plastic Carry Bags',
    slug: 'plastic-carry-bags',
    description: 'Durable and versatile plastic carry bags tailored for retail, grocery, and commercial use. engineered for high strength and reliability to securely hold various items without tearing. available in eco-friendly options to support sustainable business practices.',
    image: '/images/products/plastic-carry-bags-gen.png',
    categories: ['Bags'],
    features: ['Customizable sizes', 'High strength', 'Cost-effective', 'Recyclable options'],
  },
  {
    id: '2',
    name: 'Garbage Bags',
    slug: 'garbage-bags',
    description: 'Heavy-duty garbage bags specifically designed for residential, commercial, and industrial waste management. features leak-proof and tear-resistant properties to handle heavy and wet waste with ease. available in various capacities and eco-friendly variants for responsible disposal.',
    image: '/images/products/garbage-bags.png',
    categories: ['Bags', 'Eco-Friendly'],
    features: ['Leak-proof', 'Tear-resistant', 'Various capacities', 'Eco-friendly variants'],
  },
  {
    id: '3',
    name: 'Courier Bags',
    slug: 'courier-bags',
    description: 'Secure and tamper-evident courier bags ideal for e-commerce, logistics, and postal services. equipped with a strong adhesive seal to ensure contents remain confidential and protected. lightweight and water-resistant, saving on shipping costs while shielding against elements.',
    image: '/images/products/courier-bags.png',
    categories: ['Bags'],
    features: ['Tamper-proof seal', 'Water-resistant', 'Lightweight', 'Custom printing available'],
  },
  {
    id: '4',
    name: 'Ice Bags',
    slug: 'ice-bags',
    description: 'Premium food-grade ice packaging bags designed for the safe storage and transportation of ice. featuring strong sealing technology to prevent leaks and ensure durability at low temperatures. transparent material allows for easy visibility of contents, ideal for commercial use.',
    image: '/images/products/ice-bags.png',
    categories: ['Bags'],
    features: ['Food-grade material', 'Strong sealing', 'Transparent', 'Various sizes'],
  },
  {
    id: '5',
    name: 'Plastic Films',
    slug: 'plastic-films',
    description: 'Versatile plastic films engineered for a wide range of packaging, lamination, and protective applications. offers high clarity and excellent barrier properties to preserve product quality and freshness. customizable in thickness and grades to meet specific industrial requirements.',
    image: '/images/products/plastic-films.png',
    categories: ['Films'],
    features: ['High clarity', 'Excellent barrier properties', 'Customizable thickness', 'Multiple grades'],
  },
  {
    id: '6',
    name: 'Stretch Wrap',
    slug: 'stretch-wrap',
    description: 'High-performance stretch wrap film designed for securing pallet loads during shipping and storage. provides superior load stability and puncture resistance to protect goods from damage and dust. highly elastic and cost-effective, ensuring a tight grip for all your logistics needs.',
    image: '/images/products/stretch-wrap.png',
    categories: ['Films'],
    features: ['Superior load stability', 'Puncture-resistant', 'High stretch ratio', 'Cost-effective'],
  },
  {
    id: '7',
    name: 'PVC Shrink Film',
    slug: 'pvc-shrink',
    description: 'Premium PVC shrink film that delivers a professional finish for product bundling and display. offers uniform shrinkage and excellent clarity to enhance the visual appeal of your packaging. forms a strong, protective seal that is durable and FDA compliant for safety.',
    image: '/images/products/pvc-shrink.png',
    categories: ['Films'],
    features: ['Excellent clarity', 'Uniform shrinkage', 'Strong sealing', 'FDA compliant'],
  },
  {
    id: '9',
    name: 'Lamination Film',
    slug: 'lamination-film',
    description: 'High-quality lamination films perfect for flexible packaging, printing, and preserving documents. provides excellent adhesion and a protective moisture barrier to extend the life of your products. heat-sealable and printable, offering a versatile solution for various industrial needs.',
    image: '/images/products/lamination-film.png',
    categories: ['Films'],
    features: ['Excellent adhesion', 'Heat-sealable', 'Printable surface', 'Moisture barrier'],
  },
  {
    id: '10',
    name: 'Transparent Plastic Sheets',
    slug: 'transparent-sheets',
    description: 'Crystal-clear plastic sheets suitable for glazing, signage, and various protective applications. highly impact-resistant and weather-proof, making them a durable alternative to glass. easy to fabricate and cut, providing flexibility for custom designs and projects.',
    image: '/images/products/Transperent plastic sheet.jpeg',
    categories: ['Specialty'],
    features: ['High transparency', 'Impact-resistant', 'Weather-proof', 'Easy to fabricate'],
  },
  {
    id: '12',
    name: 'Pharmaceutical Packaging',
    slug: 'pharmaceutical-packaging',
    description: 'Medical-grade packaging materials manufactured to meet stringent pharmaceutical safety standards. provides a superior moisture barrier and tamper-evident features to ensure product integrity. available with child-resistant options, prioritizing safety and compliance in healthcare.',
    image: '/images/products/pharmaceutical-packaging-new.png',
    categories: ['Specialty'],
    features: ['GMP certified', 'Moisture barrier', 'Tamper-evident', 'Child-resistant options'],
  },
  {
    id: '13',
    name: 'Oxo-Biodegradable Products',
    slug: 'oxo-biodegradable',
    description: 'Environmentally responsible packaging solutions formulated to degrade naturally over a set timeframe. maintains the same strength and durability as conventional plastics while reducing ecological impact. certified materials ensure safety and compliance with global environmental standards.',
    image: '/images/products/oxo-biodegradable-new.png',
    categories: ['Bags', 'Eco-Friendly'],
    features: ['Eco-friendly', 'Controlled degradation', 'Same strength as conventional', 'Certified materials'],
  },
  {
    id: '14',
    name: 'Compostable Bags',
    slug: 'compostable-bags',
    description: 'Fully compostable bags made from renewable plant-based materials that break down naturally. certified biodegradable, leaving zero microplastics or harmful residues in the environment. offers a sustainable alternative for waste disposal without compromising on strength.',
    image: '/images/products/compostable-bags-new.png',
    categories: ['Bags', 'Eco-Friendly'],
    features: ['100% compostable', 'Plant-based materials', 'Certified biodegradable', 'Zero microplastics'],
  },
  {
    id: '15',
    name: 'Nursery Bags',
    slug: 'nursery-bags',
    description: 'Specialized grow bags designed for nurseries and agriculture to promote optimal plant development. features UV stabilization and drainage holes to ensure healthy root growth in various climates. constructed from durable materials to withstand outdoor conditions and handling.',
    image: '/images/products/nursery-bags-new.png',
    categories: ['Bags', 'Agricultural'],
    features: ['UV stabilized', 'Drainage holes', 'Various sizes', 'Durable construction'],
  },
  {
    id: '16',
    name: 'Blue Non-Perforated Release Film',
    slug: 'blue-release-film',
    description: 'High-quality blue release film engineered for composite manufacturing and industrial mold applications. features a non-perforated surface that ensures easy release and minimal residue transfer. heat-resistant and reusable, providing a cost-effective solution for complex fabrication processes.',
    image: '/images/products/blue-release-film-new.png',
    categories: ['Films', 'Specialty'],
    features: ['Non-perforated surface', 'Easy release', 'Heat-resistant', 'Reusable'],
  },
  {
    id: '17',
    name: 'Conducting Plastic Sheets',
    slug: 'conducting-sheets',
    description: 'Anti-static conductive plastic sheets designed for safe electronics packaging and sensitive environments. provides reliable ESD protection by controlling surface resistivity to prevent static damage. ideal for manufacturing and transporting electronic components with maximum safety.',
    image: '/images/products/conducting-sheets-gen.png',
    categories: ['Films', 'Specialty'],
    features: ['Anti-static properties', 'ESD protection', 'Surface resistivity controlled', 'Electronics-grade'],
  },
  {
    id: '18',
    name: 'Frosted Films / Bags',
    slug: 'frosted-films',
    description: 'Premium frosted finish films that provide a sophisticated look and added privacy for packaging. features a soft-touch matte surface that is highly durable and resistant to fingerprints. enhances the perceived value of products, making it perfect for luxury and retail branding.',
    image: '/images/products/Frostedbag.png',
    categories: ['Films', 'Bags', 'Specialty'],
    features: ['Matte finish', 'Soft touch', 'High durability', 'Premium look'],
  },
  {
    id: '19',
    name: 'Zippers bags',
    slug: 'zippers-sliders',
    description: 'High-quality plastic zipper bags offering reliable reclosable solutions for various packaging needs. designed with smooth-operating zippers that provide a durable and airtight seal every time. available in multiple sizes and custom colors to suit different product requirements.',
    image: '/images/products/zipper.png',
    categories: ['Bags', 'Specialty'],
    features: ['Smooth operation', 'Durable seal', 'Various sizes', 'Custom colors'],
  },
  {
    id: '20',
    name: 'Slider bags',
    slug: 'slider-bags',
    description: 'Convenient plastic slider bags designed for easy-to-use reclosable packaging applications. features a smooth sliding mechanism that ensures a secure seal to keep contents fresh. versatile and durable, making them ideal for storing food, travel items, and organization.',
    image: '/images/products/Slider bag.jpeg',
    categories: ['Bags', 'Specialty'],
    features: ['Smooth operation', 'Durable seal', 'Various sizes', 'Custom colors'],
  },
  {
    id: '21',
    name: 'Lamination Pouch',
    slug: 'lamination-pouch',
    description: 'High-clarity lamination pouches designed to protect documents from moisture, tearing, and wear. Features a strong adhesive seal for long-lasting durability and a professional finish. Available in various sizes and thicknesses to suit all your document preservation needs.',
    image: '/images/products/lamination-pouch.png',
    categories: ['Specialty'],
    features: ['High clarity', 'Strong adhesive', 'Durable protection', 'Various sizes'],
  },
  {
    id: '23',
    name: 'Ld Shrink Film',
    slug: 'ld-shrink-film',
    description: 'Low-density polyethylene shrink film offering excellent strength and tight wrapping for secure bundling. Provides superior clarity and puncture resistance, making it ideal for retail and industrial packaging. Ensures product integrity and stability during storage and transportation.',
    image: '/images/products/ld-shrink-film.png',
    categories: ['Films'],
    features: ['High strength', 'Puncture resistant', 'Tight wrap', 'Clear visibility'],
  },
  {
    id: '24',
    name: 'Poly-oly Shrink Film',
    slug: 'poly-oly-shrink-film',
    description: 'Versatile polyolefin shrink film known for its high clarity, strength, and soft touch. perfect for packaging regular and irregularly shaped items with a tight, professional finish. eco-friendly and food-safe, making it suitable for a wide range of consumer products.',
    image: '/images/products/poly-oly-shrink-film-gen.png',
    categories: ['Films'],
    features: ['Soft touch', 'High clarity', 'Food safe', 'Versatile application'],
  },
  {
    id: '25',
    name: 'Bubble Film',
    slug: 'bubble-film',
    description: 'Protective air bubble film designed to cushion fragile items against shocks and vibrations. lightweight and flexible, it easily wraps around products of all shapes for maximum safety. essential for secure shipping, moving, and storage of delicate goods.',
    image: '/images/products/bubble-film.png',
    categories: ['Films', 'Specialty'],
    features: ['Shock absorption', 'Lightweight', 'Flexible', 'Protective cushioning'],
  },
  {
    id: '26',
    name: 'Bopp Bags',
    slug: 'bopp-bags',
    description: 'Crystal-clear BOPP bags that enhance product visibility and shelf appeal for retail environments. features high tensile strength and a moisture-resistant barrier to keep contents fresh. ideal for packaging textiles, stationery, and food items with a premium look.',
    image: '/images/products/bopp-bags.png',
    categories: ['Bags'],
    features: ['High transparency', 'Tensile strength', 'Moisture resistant', 'Premium finish'],
  },
  {
    id: '27',
    name: 'Hm/ld/pe Industrial Packing Bag',
    slug: 'industrial-packing-bag',
    description: 'Robust industrial packing bags made from HM, LD, or PE materials for heavy-duty usage. designed to withstand rough handling and extreme conditions while protecting contents from dust and moisture. available in various thicknesses and sizes to meet diverse industrial packaging requirements.',
    image: '/images/products/industrial-packing-bag-gen.png',
    categories: ['Bags'],
    features: ['Heavy-duty', 'Dust proof', 'Moisture proof', 'Impact resistant'],
  },
  {
    id: '31',
    name: 'PVC Clear Bag',
    slug: 'pvc-clear-bag',
    description: 'Transparent PVC bags providing high visibility and durability for showcasing premium products. strong and flexible, these bags protect against dust and moisture while displaying contents clearly. widely used for packaging bedding, cosmetics, and promotional items.',
    image: '/images/products/zipper.png',
    categories: ['Bags'],
    features: ['High visibility', 'Flexible', 'Durable protection', 'Premium display'],
  },
  {
    id: '32',
    name: 'Extra Transparent Ld Bag',
    slug: 'extra-transparent-ld-bag',
    description: 'Ultra-clear low-density polyethylene bags designed for maximum product visibility and appeal. soft, flexible, and strong, offering reliable protection without compromising on clarity. perfect for retail display packaging where seeing the product is essential.',
    image: '/images/products/pvc-shrink.png',
    categories: ['Bags'],
    features: ['Ultra clear', 'Soft & flexible', 'Product visibility', 'Protective'],
  },
  {
    id: '33',
    name: 'VCI Films',
    slug: 'vci-films',
    description: 'Specialized VCI (Volatile Corrosion Inhibitor) films infused with active chemical compounds that prevent metals from rusting and corroding. widely used in manufacturing, shipping, and storage to shield metal parts from moisture, oxygen, and atmospheric contaminants. delivers clean, dry, residue-free protection without the need for oils or greases.',
    image: '/images/products/VCI Films.png',
    categories: ['Films', 'Specialty'],
    features: ['Active corrosion protection', 'Moisture & oxygen barrier', 'Residue-free protection', 'Ideal for metal parts'],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((product) => product.categories.includes(category));
}
